import '~/common/styles/globals.css';

import type { Metadata } from 'next';

import { Toaster } from '~/common/components/ui/sonner';
import { cn } from '~/common/helpers/cn';
import { fontSans } from '~/common/styles/fonts';
import { NextAuthProvider } from '~/core/auth/providers/next-auth-provider';
import { TRPCReactProvider } from '~/core/trpc/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-svh font-sans antialiased', fontSans.variable)}
      >
        <TRPCReactProvider>
          <NextAuthProvider>
            <div className="relative flex min-h-screen flex-col bg-background">
              {children}
            </div>
          </NextAuthProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
